- id: circleci-config-validate
  name: CircleCI config validator
  description: Validates CircleCI configuration files locally
  entry: hooks/circleci-config-validate.sh
  language: [script]
  files: ^.circleci/config.ya?ml$
