- id: circleci-config-validate
  name: circleci config validate
  description: Test if the CircleCI config file is well formed.
  entry: hooks/circleci-config-validate.sh
  language: [script]
  files: ^.circleci/config.ya?ml$
